package com.starskyxiii.collapsible_groups.defaults.integration;

import com.starskyxiii.collapsible_groups.platform.Services;
import com.starskyxiii.collapsible_groups.core.Filters;
import com.starskyxiii.collapsible_groups.core.GroupDefinition;
import com.starskyxiii.collapsible_groups.core.GroupFilter;
import com.starskyxiii.collapsible_groups.defaults.DefaultGroupProvider;
import static com.starskyxiii.collapsible_groups.defaults.DefaultGroupProvider.*;

import java.util.List;

/**
 * Built-in groups for Chipped block variants, one group per tag.
 * Automatically skipped if Chipped is not installed.
 */
public final class Chipped implements DefaultGroupProvider {

	@Override
	public int priority() {
		return 500;
	}

	private static GroupFilter chippedTag(String tag) {
		return Filters.all(Filters.itemTag(tag), Filters.itemNamespace("chipped"));
	}

	@Override
	public List<GroupDefinition> getGroups() {
		if (!Services.CONFIG.shouldLoadChipped()) return List.of();
		return List.of(
            group("__default_chipped_acacia_door", "Chipped: Acacia Door", chippedTag("chipped:acacia_door")),
            group("__default_chipped_acacia_leaves", "Chipped: Acacia Leaves", chippedTag("chipped:acacia_leaves")),
            group("__default_chipped_acacia_log", "Chipped: Acacia Log", chippedTag("chipped:acacia_log")),
            group("__default_chipped_acacia_planks", "Chipped: Acacia Planks", chippedTag("chipped:acacia_planks")),
            group("__default_chipped_acacia_trapdoor", "Chipped: Acacia Trapdoor", chippedTag("chipped:acacia_trapdoor")),
            group("__default_chipped_amethyst_block", "Chipped: Amethyst Block", chippedTag("chipped:amethyst_block")),
            group("__default_chipped_ancient_debris", "Chipped: Ancient Debris", chippedTag("chipped:ancient_debris")),
            group("__default_chipped_andesite", "Chipped: Andesite", chippedTag("chipped:andesite")),
            group("__default_chipped_bamboo_door", "Chipped: Bamboo Door", chippedTag("chipped:bamboo_door")),
            group("__default_chipped_bamboo_planks", "Chipped: Bamboo Planks", chippedTag("chipped:bamboo_planks")),
            group("__default_chipped_bamboo_trapdoor", "Chipped: Bamboo Trapdoor", chippedTag("chipped:bamboo_trapdoor")),
            group("__default_chipped_barrel", "Chipped: Barrel", chippedTag("chipped:barrel")),
            group("__default_chipped_basalt", "Chipped: Basalt", chippedTag("chipped:basalt")),
            group("__default_chipped_birch_door", "Chipped: Birch Door", chippedTag("chipped:birch_door")),
            group("__default_chipped_birch_leaves", "Chipped: Birch Leaves", chippedTag("chipped:birch_leaves")),
            group("__default_chipped_birch_log", "Chipped: Birch Log", chippedTag("chipped:birch_log")),
            group("__default_chipped_birch_planks", "Chipped: Birch Planks", chippedTag("chipped:birch_planks")),
            group("__default_chipped_birch_trapdoor", "Chipped: Birch Trapdoor", chippedTag("chipped:birch_trapdoor")),
            group("__default_chipped_black_carpet", "Chipped: Black Carpet", chippedTag("chipped:black_carpet")),
            group("__default_chipped_black_concrete", "Chipped: Black Concrete", chippedTag("chipped:black_concrete")),
            group("__default_chipped_black_glazed_terracotta", "Chipped: Black Glazed Terracotta", chippedTag("chipped:black_glazed_terracotta")),
            group("__default_chipped_black_stained_glass", "Chipped: Black Stained Glass", chippedTag("chipped:black_stained_glass")),
            group("__default_chipped_black_stained_glass_pane", "Chipped: Black Stained Glass Pane", chippedTag("chipped:black_stained_glass_pane")),
            group("__default_chipped_black_terracotta", "Chipped: Black Terracotta", chippedTag("chipped:black_terracotta")),
            group("__default_chipped_black_wool", "Chipped: Black Wool", chippedTag("chipped:black_wool")),
            group("__default_chipped_blackstone", "Chipped: Blackstone", chippedTag("chipped:blackstone")),
            group("__default_chipped_blue_carpet", "Chipped: Blue Carpet", chippedTag("chipped:blue_carpet")),
            group("__default_chipped_blue_concrete", "Chipped: Blue Concrete", chippedTag("chipped:blue_concrete")),
            group("__default_chipped_blue_glazed_terracotta", "Chipped: Blue Glazed Terracotta", chippedTag("chipped:blue_glazed_terracotta")),
            group("__default_chipped_blue_ice", "Chipped: Blue Ice", chippedTag("chipped:blue_ice")),
            group("__default_chipped_blue_stained_glass", "Chipped: Blue Stained Glass", chippedTag("chipped:blue_stained_glass")),
            group("__default_chipped_blue_stained_glass_pane", "Chipped: Blue Stained Glass Pane", chippedTag("chipped:blue_stained_glass_pane")),
            group("__default_chipped_blue_terracotta", "Chipped: Blue Terracotta", chippedTag("chipped:blue_terracotta")),
            group("__default_chipped_blue_wool", "Chipped: Blue Wool", chippedTag("chipped:blue_wool")),
            group("__default_chipped_bone_block", "Chipped: Bone Block", chippedTag("chipped:bone_block")),
            group("__default_chipped_bookshelf", "Chipped: Bookshelf", chippedTag("chipped:bookshelf")),
            group("__default_chipped_borderless_bricks", "Chipped: Borderless Bricks", chippedTag("chipped:borderless_bricks")),
            group("__default_chipped_bricks", "Chipped: Bricks", chippedTag("chipped:bricks")),
            group("__default_chipped_brown_carpet", "Chipped: Brown Carpet", chippedTag("chipped:brown_carpet")),
            group("__default_chipped_brown_concrete", "Chipped: Brown Concrete", chippedTag("chipped:brown_concrete")),
            group("__default_chipped_brown_glazed_terracotta", "Chipped: Brown Glazed Terracotta", chippedTag("chipped:brown_glazed_terracotta")),
            group("__default_chipped_brown_mushroom", "Chipped: Brown Mushroom", chippedTag("chipped:brown_mushroom")),
            group("__default_chipped_brown_mushroom_block", "Chipped: Brown Mushroom Block", chippedTag("chipped:brown_mushroom_block")),
            group("__default_chipped_brown_stained_glass", "Chipped: Brown Stained Glass", chippedTag("chipped:brown_stained_glass")),
            group("__default_chipped_brown_stained_glass_pane", "Chipped: Brown Stained Glass Pane", chippedTag("chipped:brown_stained_glass_pane")),
            group("__default_chipped_brown_terracotta", "Chipped: Brown Terracotta", chippedTag("chipped:brown_terracotta")),
            group("__default_chipped_brown_wool", "Chipped: Brown Wool", chippedTag("chipped:brown_wool")),
            group("__default_chipped_calcite", "Chipped: Calcite", chippedTag("chipped:calcite")),
            group("__default_chipped_carved_pumpkin", "Chipped: Carved Pumpkin", chippedTag("chipped:carved_pumpkin")),
            group("__default_chipped_cherry_door", "Chipped: Cherry Door", chippedTag("chipped:cherry_door")),
            group("__default_chipped_cherry_log", "Chipped: Cherry Log", chippedTag("chipped:cherry_log")),
            group("__default_chipped_cherry_planks", "Chipped: Cherry Planks", chippedTag("chipped:cherry_planks")),
            group("__default_chipped_cherry_trapdoor", "Chipped: Cherry Trapdoor", chippedTag("chipped:cherry_trapdoor")),
            group("__default_chipped_clay", "Chipped: Clay", chippedTag("chipped:clay")),
            group("__default_chipped_coal_block", "Chipped: Coal Block", chippedTag("chipped:coal_block")),
            group("__default_chipped_cobblestone", "Chipped: Cobblestone", chippedTag("chipped:cobblestone")),
            group("__default_chipped_cobweb", "Chipped: Cobweb", chippedTag("chipped:cobweb")),
            group("__default_chipped_crimson_door", "Chipped: Crimson Door", chippedTag("chipped:crimson_door")),
            group("__default_chipped_crimson_fungus", "Chipped: Crimson Fungus", chippedTag("chipped:crimson_fungus")),
            group("__default_chipped_crimson_planks", "Chipped: Crimson Planks", chippedTag("chipped:crimson_planks")),
            group("__default_chipped_crimson_roots", "Chipped: Crimson Roots", chippedTag("chipped:crimson_roots")),
            group("__default_chipped_crimson_stem", "Chipped: Crimson Stem", chippedTag("chipped:crimson_stem")),
            group("__default_chipped_crimson_trapdoor", "Chipped: Crimson Trapdoor", chippedTag("chipped:crimson_trapdoor")),
            group("__default_chipped_crying_obsidian", "Chipped: Crying Obsidian", chippedTag("chipped:crying_obsidian")),
            group("__default_chipped_cyan_carpet", "Chipped: Cyan Carpet", chippedTag("chipped:cyan_carpet")),
            group("__default_chipped_cyan_concrete", "Chipped: Cyan Concrete", chippedTag("chipped:cyan_concrete")),
            group("__default_chipped_cyan_glazed_terracotta", "Chipped: Cyan Glazed Terracotta", chippedTag("chipped:cyan_glazed_terracotta")),
            group("__default_chipped_cyan_stained_glass", "Chipped: Cyan Stained Glass", chippedTag("chipped:cyan_stained_glass")),
            group("__default_chipped_cyan_stained_glass_pane", "Chipped: Cyan Stained Glass Pane", chippedTag("chipped:cyan_stained_glass_pane")),
            group("__default_chipped_cyan_terracotta", "Chipped: Cyan Terracotta", chippedTag("chipped:cyan_terracotta")),
            group("__default_chipped_cyan_wool", "Chipped: Cyan Wool", chippedTag("chipped:cyan_wool")),
            group("__default_chipped_dark_oak_door", "Chipped: Dark Oak Door", chippedTag("chipped:dark_oak_door")),
            group("__default_chipped_dark_oak_leaves", "Chipped: Dark Oak Leaves", chippedTag("chipped:dark_oak_leaves")),
            group("__default_chipped_dark_oak_log", "Chipped: Dark Oak Log", chippedTag("chipped:dark_oak_log")),
            group("__default_chipped_dark_oak_planks", "Chipped: Dark Oak Planks", chippedTag("chipped:dark_oak_planks")),
            group("__default_chipped_dark_oak_trapdoor", "Chipped: Dark Oak Trapdoor", chippedTag("chipped:dark_oak_trapdoor")),
            group("__default_chipped_dark_prismarine", "Chipped: Dark Prismarine", chippedTag("chipped:dark_prismarine")),
            group("__default_chipped_deepslate", "Chipped: Deepslate", chippedTag("chipped:deepslate")),
            group("__default_chipped_diamond_block", "Chipped: Diamond Block", chippedTag("chipped:diamond_block")),
            group("__default_chipped_diorite", "Chipped: Diorite", chippedTag("chipped:diorite")),
            group("__default_chipped_dirt", "Chipped: Dirt", chippedTag("chipped:dirt")),
            group("__default_chipped_dried_kelp_block", "Chipped: Dried Kelp Block", chippedTag("chipped:dried_kelp_block")),
            group("__default_chipped_dripstone_block", "Chipped: Dripstone Block", chippedTag("chipped:dripstone_block")),
            group("__default_chipped_emerald_block", "Chipped: Emerald Block", chippedTag("chipped:emerald_block")),
            group("__default_chipped_end_stone", "Chipped: End Stone", chippedTag("chipped:end_stone")),
            group("__default_chipped_gilded_blackstone", "Chipped: Gilded Blackstone", chippedTag("chipped:gilded_blackstone")),
            group("__default_chipped_glass", "Chipped: Glass", chippedTag("chipped:glass")),
            group("__default_chipped_glass_pane", "Chipped: Glass Pane", chippedTag("chipped:glass_pane")),
            group("__default_chipped_glowstone", "Chipped: Glowstone", chippedTag("chipped:glowstone")),
            group("__default_chipped_gold_block", "Chipped: Gold Block", chippedTag("chipped:gold_block")),
            group("__default_chipped_granite", "Chipped: Granite", chippedTag("chipped:granite")),
            group("__default_chipped_gravel", "Chipped: Gravel", chippedTag("chipped:gravel")),
            group("__default_chipped_gray_carpet", "Chipped: Gray Carpet", chippedTag("chipped:gray_carpet")),
            group("__default_chipped_gray_concrete", "Chipped: Gray Concrete", chippedTag("chipped:gray_concrete")),
            group("__default_chipped_gray_glazed_terracotta", "Chipped: Gray Glazed Terracotta", chippedTag("chipped:gray_glazed_terracotta")),
            group("__default_chipped_gray_stained_glass", "Chipped: Gray Stained Glass", chippedTag("chipped:gray_stained_glass")),
            group("__default_chipped_gray_stained_glass_pane", "Chipped: Gray Stained Glass Pane", chippedTag("chipped:gray_stained_glass_pane")),
            group("__default_chipped_gray_terracotta", "Chipped: Gray Terracotta", chippedTag("chipped:gray_terracotta")),
            group("__default_chipped_gray_wool", "Chipped: Gray Wool", chippedTag("chipped:gray_wool")),
            group("__default_chipped_green_carpet", "Chipped: Green Carpet", chippedTag("chipped:green_carpet")),
            group("__default_chipped_green_concrete", "Chipped: Green Concrete", chippedTag("chipped:green_concrete")),
            group("__default_chipped_green_glazed_terracotta", "Chipped: Green Glazed Terracotta", chippedTag("chipped:green_glazed_terracotta")),
            group("__default_chipped_green_stained_glass", "Chipped: Green Stained Glass", chippedTag("chipped:green_stained_glass")),
            group("__default_chipped_green_stained_glass_pane", "Chipped: Green Stained Glass Pane", chippedTag("chipped:green_stained_glass_pane")),
            group("__default_chipped_green_terracotta", "Chipped: Green Terracotta", chippedTag("chipped:green_terracotta")),
            group("__default_chipped_green_wool", "Chipped: Green Wool", chippedTag("chipped:green_wool")),
            group("__default_chipped_hay_block", "Chipped: Hay Block", chippedTag("chipped:hay_block")),
            group("__default_chipped_ice", "Chipped: Ice", chippedTag("chipped:ice")),
            group("__default_chipped_iron_bars", "Chipped: Iron Bars", chippedTag("chipped:iron_bars")),
            group("__default_chipped_iron_block", "Chipped: Iron Block", chippedTag("chipped:iron_block")),
            group("__default_chipped_jack_o_lantern", "Chipped: Jack O Lantern", chippedTag("chipped:jack_o_lantern")),
            group("__default_chipped_jungle_door", "Chipped: Jungle Door", chippedTag("chipped:jungle_door")),
            group("__default_chipped_jungle_leaves", "Chipped: Jungle Leaves", chippedTag("chipped:jungle_leaves")),
            group("__default_chipped_jungle_log", "Chipped: Jungle Log", chippedTag("chipped:jungle_log")),
            group("__default_chipped_jungle_planks", "Chipped: Jungle Planks", chippedTag("chipped:jungle_planks")),
            group("__default_chipped_jungle_trapdoor", "Chipped: Jungle Trapdoor", chippedTag("chipped:jungle_trapdoor")),
            group("__default_chipped_ladder", "Chipped: Ladder", chippedTag("chipped:ladder")),
            group("__default_chipped_lantern", "Chipped: Lantern", chippedTag("chipped:lantern")),
            group("__default_chipped_lapis_block", "Chipped: Lapis Block", chippedTag("chipped:lapis_block")),
            group("__default_chipped_light_blue_carpet", "Chipped: Light Blue Carpet", chippedTag("chipped:light_blue_carpet")),
            group("__default_chipped_light_blue_concrete", "Chipped: Light Blue Concrete", chippedTag("chipped:light_blue_concrete")),
            group("__default_chipped_light_blue_glazed_terracotta", "Chipped: Light Blue Glazed Terracotta", chippedTag("chipped:light_blue_glazed_terracotta")),
            group("__default_chipped_light_blue_stained_glass", "Chipped: Light Blue Stained Glass", chippedTag("chipped:light_blue_stained_glass")),
            group("__default_chipped_light_blue_stained_glass_pane", "Chipped: Light Blue Stained Glass Pane", chippedTag("chipped:light_blue_stained_glass_pane")),
            group("__default_chipped_light_blue_terracotta", "Chipped: Light Blue Terracotta", chippedTag("chipped:light_blue_terracotta")),
            group("__default_chipped_light_blue_wool", "Chipped: Light Blue Wool", chippedTag("chipped:light_blue_wool")),
            group("__default_chipped_light_gray_carpet", "Chipped: Light Gray Carpet", chippedTag("chipped:light_gray_carpet")),
            group("__default_chipped_light_gray_concrete", "Chipped: Light Gray Concrete", chippedTag("chipped:light_gray_concrete")),
            group("__default_chipped_light_gray_glazed_terracotta", "Chipped: Light Gray Glazed Terracotta", chippedTag("chipped:light_gray_glazed_terracotta")),
            group("__default_chipped_light_gray_stained_glass", "Chipped: Light Gray Stained Glass", chippedTag("chipped:light_gray_stained_glass")),
            group("__default_chipped_light_gray_stained_glass_pane", "Chipped: Light Gray Stained Glass Pane", chippedTag("chipped:light_gray_stained_glass_pane")),
            group("__default_chipped_light_gray_terracotta", "Chipped: Light Gray Terracotta", chippedTag("chipped:light_gray_terracotta")),
            group("__default_chipped_light_gray_wool", "Chipped: Light Gray Wool", chippedTag("chipped:light_gray_wool")),
            group("__default_chipped_lily_pad", "Chipped: Lily Pad", chippedTag("chipped:lily_pad")),
            group("__default_chipped_lime_carpet", "Chipped: Lime Carpet", chippedTag("chipped:lime_carpet")),
            group("__default_chipped_lime_concrete", "Chipped: Lime Concrete", chippedTag("chipped:lime_concrete")),
            group("__default_chipped_lime_glazed_terracotta", "Chipped: Lime Glazed Terracotta", chippedTag("chipped:lime_glazed_terracotta")),
            group("__default_chipped_lime_stained_glass", "Chipped: Lime Stained Glass", chippedTag("chipped:lime_stained_glass")),
            group("__default_chipped_lime_stained_glass_pane", "Chipped: Lime Stained Glass Pane", chippedTag("chipped:lime_stained_glass_pane")),
            group("__default_chipped_lime_terracotta", "Chipped: Lime Terracotta", chippedTag("chipped:lime_terracotta")),
            group("__default_chipped_lime_wool", "Chipped: Lime Wool", chippedTag("chipped:lime_wool")),
            group("__default_chipped_lodestone", "Chipped: Lodestone", chippedTag("chipped:lodestone")),
            group("__default_chipped_magenta_carpet", "Chipped: Magenta Carpet", chippedTag("chipped:magenta_carpet")),
            group("__default_chipped_magenta_concrete", "Chipped: Magenta Concrete", chippedTag("chipped:magenta_concrete")),
            group("__default_chipped_magenta_glazed_terracotta", "Chipped: Magenta Glazed Terracotta", chippedTag("chipped:magenta_glazed_terracotta")),
            group("__default_chipped_magenta_stained_glass", "Chipped: Magenta Stained Glass", chippedTag("chipped:magenta_stained_glass")),
            group("__default_chipped_magenta_stained_glass_pane", "Chipped: Magenta Stained Glass Pane", chippedTag("chipped:magenta_stained_glass_pane")),
            group("__default_chipped_magenta_terracotta", "Chipped: Magenta Terracotta", chippedTag("chipped:magenta_terracotta")),
            group("__default_chipped_magenta_wool", "Chipped: Magenta Wool", chippedTag("chipped:magenta_wool")),
            group("__default_chipped_magma_block", "Chipped: Magma Block", chippedTag("chipped:magma_block")),
            group("__default_chipped_mangrove_door", "Chipped: Mangrove Door", chippedTag("chipped:mangrove_door")),
            group("__default_chipped_mangrove_log", "Chipped: Mangrove Log", chippedTag("chipped:mangrove_log")),
            group("__default_chipped_mangrove_planks", "Chipped: Mangrove Planks", chippedTag("chipped:mangrove_planks")),
            group("__default_chipped_mangrove_roots", "Chipped: Mangrove Roots", chippedTag("chipped:mangrove_roots")),
            group("__default_chipped_mangrove_trapdoor", "Chipped: Mangrove Trapdoor", chippedTag("chipped:mangrove_trapdoor")),
            group("__default_chipped_melon", "Chipped: Melon", chippedTag("chipped:melon")),
            group("__default_chipped_moss_block", "Chipped: Moss Block", chippedTag("chipped:moss_block")),
            group("__default_chipped_mossy_cobblestone", "Chipped: Mossy Cobblestone", chippedTag("chipped:mossy_cobblestone")),
            group("__default_chipped_mossy_stone_bricks", "Chipped: Mossy Stone Bricks", chippedTag("chipped:mossy_stone_bricks")),
            group("__default_chipped_mud", "Chipped: Mud", chippedTag("chipped:mud")),
            group("__default_chipped_mud_bricks", "Chipped: Mud Bricks", chippedTag("chipped:mud_bricks")),
            group("__default_chipped_mushroom_stem", "Chipped: Mushroom Stem", chippedTag("chipped:mushroom_stem")),
            group("__default_chipped_nether_bricks", "Chipped: Nether Bricks", chippedTag("chipped:nether_bricks")),
            group("__default_chipped_nether_sprouts", "Chipped: Nether Sprouts", chippedTag("chipped:nether_sprouts")),
            group("__default_chipped_nether_wart_block", "Chipped: Nether Wart Block", chippedTag("chipped:nether_wart_block")),
            group("__default_chipped_netherite_block", "Chipped: Netherite Block", chippedTag("chipped:netherite_block")),
            group("__default_chipped_netherrack", "Chipped: Netherrack", chippedTag("chipped:netherrack")),
            group("__default_chipped_oak_door", "Chipped: Oak Door", chippedTag("chipped:oak_door")),
            group("__default_chipped_oak_leaves", "Chipped: Oak Leaves", chippedTag("chipped:oak_leaves")),
            group("__default_chipped_oak_log", "Chipped: Oak Log", chippedTag("chipped:oak_log")),
            group("__default_chipped_oak_planks", "Chipped: Oak Planks", chippedTag("chipped:oak_planks")),
            group("__default_chipped_oak_trapdoor", "Chipped: Oak Trapdoor", chippedTag("chipped:oak_trapdoor")),
            group("__default_chipped_obsidian", "Chipped: Obsidian", chippedTag("chipped:obsidian")),
            group("__default_chipped_ochre_froglight", "Chipped: Ochre Froglight", chippedTag("chipped:ochre_froglight")),
            group("__default_chipped_orange_carpet", "Chipped: Orange Carpet", chippedTag("chipped:orange_carpet")),
            group("__default_chipped_orange_concrete", "Chipped: Orange Concrete", chippedTag("chipped:orange_concrete")),
            group("__default_chipped_orange_glazed_terracotta", "Chipped: Orange Glazed Terracotta", chippedTag("chipped:orange_glazed_terracotta")),
            group("__default_chipped_orange_stained_glass", "Chipped: Orange Stained Glass", chippedTag("chipped:orange_stained_glass")),
            group("__default_chipped_orange_stained_glass_pane", "Chipped: Orange Stained Glass Pane", chippedTag("chipped:orange_stained_glass_pane")),
            group("__default_chipped_orange_terracotta", "Chipped: Orange Terracotta", chippedTag("chipped:orange_terracotta")),
            group("__default_chipped_orange_wool", "Chipped: Orange Wool", chippedTag("chipped:orange_wool")),
            group("__default_chipped_packed_ice", "Chipped: Packed Ice", chippedTag("chipped:packed_ice")),
            group("__default_chipped_packed_mud", "Chipped: Packed Mud", chippedTag("chipped:packed_mud")),
            group("__default_chipped_pearlescent_froglight", "Chipped: Pearlescent Froglight", chippedTag("chipped:pearlescent_froglight")),
            group("__default_chipped_pink_carpet", "Chipped: Pink Carpet", chippedTag("chipped:pink_carpet")),
            group("__default_chipped_pink_concrete", "Chipped: Pink Concrete", chippedTag("chipped:pink_concrete")),
            group("__default_chipped_pink_glazed_terracotta", "Chipped: Pink Glazed Terracotta", chippedTag("chipped:pink_glazed_terracotta")),
            group("__default_chipped_pink_stained_glass", "Chipped: Pink Stained Glass", chippedTag("chipped:pink_stained_glass")),
            group("__default_chipped_pink_stained_glass_pane", "Chipped: Pink Stained Glass Pane", chippedTag("chipped:pink_stained_glass_pane")),
            group("__default_chipped_pink_terracotta", "Chipped: Pink Terracotta", chippedTag("chipped:pink_terracotta")),
            group("__default_chipped_pink_wool", "Chipped: Pink Wool", chippedTag("chipped:pink_wool")),
            group("__default_chipped_pointed_dripstone", "Chipped: Pointed Dripstone", chippedTag("chipped:pointed_dripstone")),
            group("__default_chipped_prismarine", "Chipped: Prismarine", chippedTag("chipped:prismarine")),
            group("__default_chipped_pumpkin", "Chipped: Pumpkin", chippedTag("chipped:pumpkin")),
            group("__default_chipped_purple_carpet", "Chipped: Purple Carpet", chippedTag("chipped:purple_carpet")),
            group("__default_chipped_purple_concrete", "Chipped: Purple Concrete", chippedTag("chipped:purple_concrete")),
            group("__default_chipped_purple_glazed_terracotta", "Chipped: Purple Glazed Terracotta", chippedTag("chipped:purple_glazed_terracotta")),
            group("__default_chipped_purple_stained_glass", "Chipped: Purple Stained Glass", chippedTag("chipped:purple_stained_glass")),
            group("__default_chipped_purple_stained_glass_pane", "Chipped: Purple Stained Glass Pane", chippedTag("chipped:purple_stained_glass_pane")),
            group("__default_chipped_purple_terracotta", "Chipped: Purple Terracotta", chippedTag("chipped:purple_terracotta")),
            group("__default_chipped_purple_wool", "Chipped: Purple Wool", chippedTag("chipped:purple_wool")),
            group("__default_chipped_purpur_block", "Chipped: Purpur Block", chippedTag("chipped:purpur_block")),
            group("__default_chipped_quartz_block", "Chipped: Quartz Block", chippedTag("chipped:quartz_block")),
            group("__default_chipped_raw_copper_block", "Chipped: Raw Copper Block", chippedTag("chipped:raw_copper_block")),
            group("__default_chipped_raw_gold_block", "Chipped: Raw Gold Block", chippedTag("chipped:raw_gold_block")),
            group("__default_chipped_raw_iron_block", "Chipped: Raw Iron Block", chippedTag("chipped:raw_iron_block")),
            group("__default_chipped_red_carpet", "Chipped: Red Carpet", chippedTag("chipped:red_carpet")),
            group("__default_chipped_red_concrete", "Chipped: Red Concrete", chippedTag("chipped:red_concrete")),
            group("__default_chipped_red_glazed_terracotta", "Chipped: Red Glazed Terracotta", chippedTag("chipped:red_glazed_terracotta")),
            group("__default_chipped_red_mushroom", "Chipped: Red Mushroom", chippedTag("chipped:red_mushroom")),
            group("__default_chipped_red_mushroom_block", "Chipped: Red Mushroom Block", chippedTag("chipped:red_mushroom_block")),
            group("__default_chipped_red_nether_bricks", "Chipped: Red Nether Bricks", chippedTag("chipped:red_nether_bricks")),
            group("__default_chipped_red_sandstone", "Chipped: Red Sandstone", chippedTag("chipped:red_sandstone")),
            group("__default_chipped_red_stained_glass", "Chipped: Red Stained Glass", chippedTag("chipped:red_stained_glass")),
            group("__default_chipped_red_stained_glass_pane", "Chipped: Red Stained Glass Pane", chippedTag("chipped:red_stained_glass_pane")),
            group("__default_chipped_red_terracotta", "Chipped: Red Terracotta", chippedTag("chipped:red_terracotta")),
            group("__default_chipped_red_wool", "Chipped: Red Wool", chippedTag("chipped:red_wool")),
            group("__default_chipped_redstone_block", "Chipped: Redstone Block", chippedTag("chipped:redstone_block")),
            group("__default_chipped_redstone_lamp", "Chipped: Redstone Lamp", chippedTag("chipped:redstone_lamp")),
            group("__default_chipped_redstone_torch", "Chipped: Redstone Torch", chippedTag("chipped:redstone_torch")),
            group("__default_chipped_sand", "Chipped: Sand", chippedTag("chipped:sand")),
            group("__default_chipped_sandstone", "Chipped: Sandstone", chippedTag("chipped:sandstone")),
            group("__default_chipped_sea_lantern", "Chipped: Sea Lantern", chippedTag("chipped:sea_lantern")),
            group("__default_chipped_shroomlight", "Chipped: Shroomlight", chippedTag("chipped:shroomlight")),
            group("__default_chipped_smooth_stone", "Chipped: Smooth Stone", chippedTag("chipped:smooth_stone")),
            group("__default_chipped_snow_block", "Chipped: Snow Block", chippedTag("chipped:snow_block")),
            group("__default_chipped_soul_lantern", "Chipped: Soul Lantern", chippedTag("chipped:soul_lantern")),
            group("__default_chipped_soul_sand", "Chipped: Soul Sand", chippedTag("chipped:soul_sand")),
            group("__default_chipped_special_lantern", "Chipped: Special Lantern", chippedTag("chipped:special_lantern")),
            group("__default_chipped_special_soul_lantern", "Chipped: Special Soul Lantern", chippedTag("chipped:special_soul_lantern")),
            group("__default_chipped_sponge", "Chipped: Sponge", chippedTag("chipped:sponge")),
            group("__default_chipped_spruce_door", "Chipped: Spruce Door", chippedTag("chipped:spruce_door")),
            group("__default_chipped_spruce_leaves", "Chipped: Spruce Leaves", chippedTag("chipped:spruce_leaves")),
            group("__default_chipped_spruce_log", "Chipped: Spruce Log", chippedTag("chipped:spruce_log")),
            group("__default_chipped_spruce_planks", "Chipped: Spruce Planks", chippedTag("chipped:spruce_planks")),
            group("__default_chipped_spruce_trapdoor", "Chipped: Spruce Trapdoor", chippedTag("chipped:spruce_trapdoor")),
            group("__default_chipped_stone", "Chipped: Stone", chippedTag("chipped:stone")),
            group("__default_chipped_stripped_acacia_log", "Chipped: Stripped Acacia Log", chippedTag("chipped:stripped_acacia_log")),
            group("__default_chipped_stripped_birch_log", "Chipped: Stripped Birch Log", chippedTag("chipped:stripped_birch_log")),
            group("__default_chipped_stripped_cherry_log", "Chipped: Stripped Cherry Log", chippedTag("chipped:stripped_cherry_log")),
            group("__default_chipped_stripped_crimson_stem", "Chipped: Stripped Crimson Stem", chippedTag("chipped:stripped_crimson_stem")),
            group("__default_chipped_stripped_dark_oak_log", "Chipped: Stripped Dark Oak Log", chippedTag("chipped:stripped_dark_oak_log")),
            group("__default_chipped_stripped_jungle_log", "Chipped: Stripped Jungle Log", chippedTag("chipped:stripped_jungle_log")),
            group("__default_chipped_stripped_mangrove_log", "Chipped: Stripped Mangrove Log", chippedTag("chipped:stripped_mangrove_log")),
            group("__default_chipped_stripped_oak_log", "Chipped: Stripped Oak Log", chippedTag("chipped:stripped_oak_log")),
            group("__default_chipped_stripped_spruce_log", "Chipped: Stripped Spruce Log", chippedTag("chipped:stripped_spruce_log")),
            group("__default_chipped_stripped_warped_stem", "Chipped: Stripped Warped Stem", chippedTag("chipped:stripped_warped_stem")),
            group("__default_chipped_terracotta", "Chipped: Terracotta", chippedTag("chipped:terracotta")),
            group("__default_chipped_torch", "Chipped: Torch", chippedTag("chipped:torch")),
            group("__default_chipped_tuff", "Chipped: Tuff", chippedTag("chipped:tuff")),
            group("__default_chipped_verdant_froglight", "Chipped: Verdant Froglight", chippedTag("chipped:verdant_froglight")),
            group("__default_chipped_vine", "Chipped: Vine", chippedTag("chipped:vine")),
            group("__default_chipped_wall_torch", "Chipped: Wall Torch", chippedTag("chipped:wall_torch")),
            group("__default_chipped_warped_door", "Chipped: Warped Door", chippedTag("chipped:warped_door")),
            group("__default_chipped_warped_fungus", "Chipped: Warped Fungus", chippedTag("chipped:warped_fungus")),
            group("__default_chipped_warped_planks", "Chipped: Warped Planks", chippedTag("chipped:warped_planks")),
            group("__default_chipped_warped_roots", "Chipped: Warped Roots", chippedTag("chipped:warped_roots")),
            group("__default_chipped_warped_stem", "Chipped: Warped Stem", chippedTag("chipped:warped_stem")),
            group("__default_chipped_warped_trapdoor", "Chipped: Warped Trapdoor", chippedTag("chipped:warped_trapdoor")),
            group("__default_chipped_warped_wart_block", "Chipped: Warped Wart Block", chippedTag("chipped:warped_wart_block")),
            group("__default_chipped_waxed_copper_block", "Chipped: Waxed Copper Block", chippedTag("chipped:waxed_copper_block")),
            group("__default_chipped_waxed_exposed_copper_block", "Chipped: Waxed Exposed Copper Block", chippedTag("chipped:waxed_exposed_copper_block")),
            group("__default_chipped_waxed_oxidized_copper", "Chipped: Waxed Oxidized Copper", chippedTag("chipped:waxed_oxidized_copper")),
            group("__default_chipped_waxed_weathered_copper", "Chipped: Waxed Weathered Copper", chippedTag("chipped:waxed_weathered_copper")),
            group("__default_chipped_white_carpet", "Chipped: White Carpet", chippedTag("chipped:white_carpet")),
            group("__default_chipped_white_concrete", "Chipped: White Concrete", chippedTag("chipped:white_concrete")),
            group("__default_chipped_white_glazed_terracotta", "Chipped: White Glazed Terracotta", chippedTag("chipped:white_glazed_terracotta")),
            group("__default_chipped_white_stained_glass", "Chipped: White Stained Glass", chippedTag("chipped:white_stained_glass")),
            group("__default_chipped_white_stained_glass_pane", "Chipped: White Stained Glass Pane", chippedTag("chipped:white_stained_glass_pane")),
            group("__default_chipped_white_terracotta", "Chipped: White Terracotta", chippedTag("chipped:white_terracotta")),
            group("__default_chipped_white_wool", "Chipped: White Wool", chippedTag("chipped:white_wool")),
            group("__default_chipped_yellow_carpet", "Chipped: Yellow Carpet", chippedTag("chipped:yellow_carpet")),
            group("__default_chipped_yellow_concrete", "Chipped: Yellow Concrete", chippedTag("chipped:yellow_concrete")),
            group("__default_chipped_yellow_glazed_terracotta", "Chipped: Yellow Glazed Terracotta", chippedTag("chipped:yellow_glazed_terracotta")),
            group("__default_chipped_yellow_stained_glass", "Chipped: Yellow Stained Glass", chippedTag("chipped:yellow_stained_glass")),
            group("__default_chipped_yellow_stained_glass_pane", "Chipped: Yellow Stained Glass Pane", chippedTag("chipped:yellow_stained_glass_pane")),
            group("__default_chipped_yellow_terracotta", "Chipped: Yellow Terracotta", chippedTag("chipped:yellow_terracotta")),
            group("__default_chipped_yellow_wool", "Chipped: Yellow Wool", chippedTag("chipped:yellow_wool"))
		);
	}
}
